"""update user table

Revision ID: 870b21f91b3d
Revises: 
Create Date: 2023-05-25 16:54:31.197825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870b21f91b3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations_test')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='FALSE', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.create_table('locations_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='locations_test_pkey')
    )
    # ### end Alembic commands ###
